// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a DIRECT connection: Neon's pooled endpoint (pgbouncer)
    // closes the long-lived transactions DDL requires, which surfaces as
    // "P1017 Server has closed the connection". Set DIRECT_URL explicitly, or
    // let this derive it by dropping "-pooler" from the pooled host.
    url:
      process.env["DIRECT_URL"] ??
      process.env["DATABASE_URL"]?.replace("-pooler", ""),
  },
});
